/-
SYMPOSIUM CHU — dynamics layer via Wolfram model rewriting.

Fills the previously EMPTY dynamics layer of CHU (PROM 16 A2-S4, marked OPEN):
`axiom CHU : Type` had only static slicing (`CHUPiece := CHU → Prop`) and no notion
of TIME / update. Wolfram's update rule H₁→H₂ supplies exactly that.

Grounded in arXiv:2111.03460 (Arsiwalla & Gorard, "Pregeometric Spaces from Wolfram
Model Rewriting Systems as Homotopy Types", math.CT), full-text verified 2026-07-13:
  - Def 2.1  : Wolfram hypergraph H=(V,E) = finite collection of ordered relations
  - Def 2.2  : update rule (rewrite)  H₁ → H₂
  - Def 2.4  : multiway evolution graph (one-step relation + its closure)
  - Prop 4.3 : "replacing isomorphisms with STRICT EQUALITIES would collapse this tower
               of homotopies to obtain a 1-category"
  - §5.3     : Voevodsky univalence appears ONLY as PHILOSOPHICAL backing for equating
               states/paths. The paper does NOT construct untruncation via univalence —
               it uses Grothendieck's homotopy hypothesis. Any univalence invoked below
               is a CHU-side bolt-on axiom, NOT inherited from this source.
               (Corrected 2026-07-15, A2S1 pdftotext direct read.)

Central formal content of THIS file: the truncation dichotomy that answers
"why go beyond Neo4j to CHU":
  * `Reach` (Prop-valued)  = Neo4j-style strict-equality reachability = 1-category
    truncation: ALL parallel derivations are identified (proof irrelevance).
  * `Path`  (Type-valued)  = the un-truncated derivation space that RETAINS distinct
    witnesses — the 1-skeleton of a COMPUTABLE ∞-groupoid once higher homotopies
    (paths-between-paths, Prop 4.3) are added.

⚠️ This tower is NOT the Ruliad (corrected 2026-07-15). It is generated by one fixed
`RuleSet` over a computable base, whereas the Ruliad is the entangled limit over ALL
rules. The literal identification "CHU = Ruliad" is REFUTED on three independent axes —
decisively: limit-computable functions are NOT closed under the inverse limit that
assembles the Ruliad (Limit Lemma), so a computable-closed object cannot equal that
completion. The surviving relation is that CHU is the computable 1-truncation (or a
computable thread) OF the Ruliad ∞-groupoid — a truncation, not an identity.
See THEORY/CHU/PROM_16_RULIAD_GROUNDING_REPORT_2026-07-15.md;
KG lesson-chu-ruliad-identity-refuted-truncation-reframe-2026-07-15.

Mathlib-free. Verify:  lean CHU_WolframRewrite.lean   (exit 0 = PASS).

KG: prom16-wolfram-chu-ruliad-hott-2026-07-13,
    lesson-neo4j-is-strict-eq-1category-truncation-of-chu-infgroupoid-2026-07-13,
    finding-prom16-wolfram-chu-A4-S2-2026-07-13 (fork FORK_GROUNDED)
-/

namespace SymposiumCHU.Wolfram

/-- The computable hyperuniverse, opaque base (same axiom as AirplaneMan_CHU_Universe.lean). -/
axiom CHU : Type

/-- A Wolfram update rule (Def 2.2): rewrites one hyperstate to another.
    Total endofunction here for simplicity (partial matching abstracted away). -/
abbrev Rewrite : Type := CHU → CHU

/-- A rule set = the collection of admissible update rules. -/
abbrev RuleSet : Type := List Rewrite

/-- One-step multiway relation (Def 2.4): `x` steps to `y` when some rule in the set maps it. -/
inductive Step (rs : RuleSet) : CHU → CHU → Prop where
  | rule : ∀ (r : Rewrite), r ∈ rs → ∀ x, Step rs x (r x)

/-- A multiway PATH: the reflexive–transitive closure of `Step`, kept `Type`-valued so that
    distinct derivations remain distinct terms (higher structure is NOT discarded). -/
inductive Path (rs : RuleSet) : CHU → CHU → Type where
  | refl : ∀ x, Path rs x x
  | cons : ∀ {x y z}, Step rs x y → Path rs y z → Path rs x z

/-- Concatenation of histories (path composition). -/
def Path.trans {rs : RuleSet} : ∀ {x y z : CHU}, Path rs x y → Path rs y z → Path rs x z
  | _, _, _, .refl _,   q => q
  | _, _, _, .cons s p, q => .cons s (Path.trans p q)

/-! ### Groupoid-flavoured laws (the 1-skeleton of the ∞-groupoid) -/

/-- Left unit law holds definitionally. -/
theorem Path.refl_trans {rs : RuleSet} {x y : CHU} (p : Path rs x y) :
    Path.trans (Path.refl x) p = p := rfl

/-- Right unit law. -/
theorem Path.trans_refl {rs : RuleSet} {x y : CHU} (p : Path rs x y) :
    Path.trans p (Path.refl y) = p := by
  induction p with
  | refl _ => rfl
  | cons s p ih => simp only [Path.trans, ih]

/-- Associativity of composition — path space is a (higher) category, not a mere relation. -/
theorem Path.trans_assoc {rs : RuleSet} {w x y z : CHU}
    (p : Path rs w x) (q : Path rs x y) (r : Path rs y z) :
    Path.trans (Path.trans p q) r = Path.trans p (Path.trans q r) := by
  induction p with
  | refl _ => rfl
  | cons s p ih => simp only [Path.trans, ih]

/-! ### The truncation dichotomy — the formal answer to "why beyond Neo4j?"

The collapse that turns CHU's ∞-tower into a Neo4j-style 1-category is ONE phenomenon, not a
coincidence re-proved per level. We isolate it once as `Trunc` (inhabitation-only, `Prop`-valued)
and prove `Trunc.collapse` for an ARBITRARY level `A`; the level-1 and level-2 collapses below
are then literal instances rather than independent `rfl`s. -/

/-- The generic 0-truncation of a tower level: forget the witnessing term (which derivation,
    which homotopy) and keep only *whether* the level is inhabited. `Prop`-valued, so it is
    exactly the property-graph / strict-equality view. -/
def Trunc (A : Type) : Prop := Nonempty A

/-- **The truncation collapse, at EVERY level uniformly.** For any level `A` — level-1
    derivations `Path`, level-2 homotopies `Cell`, and every higher level alike — its
    inhabitation-truncation is a `Prop`, so definitional proof irrelevance identifies all
    witnesses. This single lemma *is* the whole content of Prop 4.3's "replacing isomorphisms
    with strict equalities collapses this tower ... to obtain a 1-category": the collapse is
    not special to any level, it is what `Prop`-valued truncation does everywhere. The `∀ A`
    here is precisely "at every level". `strict_truncation` (level 1) and `strict_truncation2`
    (level 2) are now literal instances. -/
theorem Trunc.collapse {A : Type} (p q : Trunc A) : p = q := rfl

/-- Neo4j-style reachability: the level-1 truncation — forget which derivation witnesses
    reachability, keep only *whether* `y` is reachable. -/
def Reach (rs : RuleSet) (x y : CHU) : Prop := Trunc (Path rs x y)

/-- **1-CATEGORY TRUNCATION (Neo4j regime), level 1 — an instance of `Trunc.collapse`.** Under
    strict propositional equality, any two parallel derivations `x ⇝ y` are *identified*: the
    whole tower of distinct histories collapses to a single arrow. A property-graph DB identifies
    nodes by strict id equality, so it lives here — a deliberate truncation, not an
    expressiveness gap. -/
theorem strict_truncation {rs : RuleSet} {x y : CHU} (p q : Reach rs x y) : p = q :=
  Trunc.collapse (A := Path rs x y) p q

/-- Lifting a genuine derivation into the truncated world (the functor Path ⟶ Reach). -/
theorem Path.toReach {rs : RuleSet} {x y : CHU} (p : Path rs x y) : Reach rs x y := ⟨p⟩

/-- Reachability composes (the truncation is still a category — just a 1-category). -/
theorem Reach.trans {rs : RuleSet} {x y z : CHU}
    (h₁ : Reach rs x y) (h₂ : Reach rs y z) : Reach rs x z :=
  match h₁, h₂ with
  | ⟨p⟩, ⟨q⟩ => ⟨Path.trans p q⟩

/-! ### Level 2 — higher homotopies (paths-between-paths) as 2-cells

Prop 4.1 / 4.2 (arXiv:2111.03460): "inducing a homotopy between two paths ... can be thought
of as introducing new higher-order rewriting rules", and these are the 2-morphisms of a double
category. We lift the level-1 pattern one dimension up: a HIGHER rule relation relates two
*parallel* level-1 paths, and 2-cells are its reflexive–transitive closure. -/

/-- A higher rewrite rule (2-morphism generator): a relation between two parallel paths.
    Abstract, exactly as `RuleSet` was abstract for the level-1 `Step`. -/
abbrev HRule (rs : RuleSet) : Type :=
  ∀ {x y : CHU}, Path rs x y → Path rs x y → Prop

/-- A 2-CELL (homotopy) between two parallel paths, generated by `hr`. `Type`-valued so that
    distinct fillings remain distinct terms — the level-2 skeleton of the ∞-tower. -/
inductive Cell (rs : RuleSet) (hr : HRule rs) :
    {x y : CHU} → Path rs x y → Path rs x y → Type where
  | id   : ∀ {x y : CHU} (p : Path rs x y), Cell rs hr p p
  | move : ∀ {x y : CHU} {p q r : Path rs x y}, hr p q → Cell rs hr q r → Cell rs hr p r

/-- Vertical composition of 2-cells (stacking homotopies). -/
def Cell.vtrans {rs : RuleSet} {hr : HRule rs} :
    ∀ {x y : CHU} {p q r : Path rs x y}, Cell rs hr p q → Cell rs hr q r → Cell rs hr p r
  | _, _, _, _, _, .id _,       c => c
  | _, _, _, _, _, .move m c₁,  c₂ => .move m (Cell.vtrans c₁ c₂)

/-- Left unit law at level 2. -/
theorem Cell.id_vtrans {rs : RuleSet} {hr : HRule rs} {x y : CHU} {p q : Path rs x y}
    (c : Cell rs hr p q) : Cell.vtrans (Cell.id p) c = c := by
  simp only [Cell.vtrans]

/-- The 0-truncation of the 2-cell space: "are these two parallel paths homotopic?"
    The level-2 instance of the same generic `Trunc`. -/
def Homotopic (rs : RuleSet) (hr : HRule rs) {x y : CHU} (p q : Path rs x y) : Prop :=
  Trunc (Cell rs hr p q)

/-- **The truncation collapse at level 2 — the SAME instance of `Trunc.collapse`, one dimension
    up** (Prop 4.3): any two homotopy-witnesses between the same pair of parallel paths are
    identified. Because it is `Trunc.collapse` re-applied (not a fresh `rfl`), the collapse is
    demonstrably not special to level 1: `Trunc.collapse`'s `∀ A` already covers every level of
    the ∞-tower. This is precisely why the un-truncated object — CHU's `Type`-valued rewrite
    tower taken under a univalent identity (a CHU-side axiom choice, NOT inherited from
    arXiv:2111.03460) — is a strictly richer structure than any of its `Prop`-truncations.
    Note it is a computable tower, not the Ruliad itself (see header, corrected 2026-07-15). -/
theorem strict_truncation2 {rs : RuleSet} {hr : HRule rs} {x y : CHU} {p q : Path rs x y}
    (h₁ h₂ : Homotopic rs hr p q) : h₁ = h₂ :=
  Trunc.collapse (A := Cell rs hr p q) h₁ h₂

/-! ### Honest boundary

Now formalised (Mathlib-free): level 1 (Rewrite / Step / Path / trans + unit·assoc) AND level 2
(HRule / Cell 2-morphisms / vtrans + unit) — the *un-truncated*, `Type`-valued tower whose
witnesses stay distinct. The collapse to the strict / Neo4j 1-category is now proven ONCE,
level-generically, as `Trunc.collapse` (`∀ A`, so it already covers every tower level); the
level-1 `strict_truncation` and level-2 `strict_truncation2` are its literal instances rather
than two separate `rfl`s. So the "strict equality discards EVERY level" claim is discharged in
full on the *truncated* side.

Still OPEN (correct, non-overclaimed boundary): the collapse is fully general, but the
un-truncated side is not. Assembling the `Type`-valued levels (`Path`, `Cell`, …) into a single
`n → ∞` colimit — the limiting object that Prop 4.4 places in the (∞,1)-CATEGORY `∞Grpd`
(Lurie); its (∞,1)-TOPOS realisation is NOT a proven Proposition there but the authors' own
hedged Remark 4.6/§5 ("may be realized"), so we must not cite it as established — needs native
higher-inductive / univalent machinery that bare Lean 4 lacks; only levels 1 and 2 are concretely
realised. The OPEN frontier is therefore now sharp: it is the un-truncated colimit, NOT the
per-level collapse. Cf. PROM 16 A4-S2 fork = FORK_GROUNDED, not FORK_CLOSED. -/

end SymposiumCHU.Wolfram
